server:
  port: 8082
  error:
    path: /error
    whitelabel:
      enabled: false


spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/hotel_service
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
      cache: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailsenderby200@gmail.com
    password: rsjzlkmcrgonsqws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    resources:
      static-locations: classpath:/static/