server:
  port: 8085

spring:
  application:
    name: ROOM-SERVICE
  datasource:
    username: postgres
    password: 1999
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

host: ${HOST:http://localhost}
services:
  notification-url: ${NOTIFICATION_URL:http://NOTIFICATION-SERVICE/notification}

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848
    access:
      expiry: 3000000
    refresh:
      expiry: 300000000