name: villaRent ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: openjdk

    steps:
    - uses: actions/checkout@v3
    - name: villarent_image
      run: docker build . --file Dockerfile --tag villarent:$(date +%s)
